version: "3.6"

x-app-opts: &app-opts
  build: .
  image: "geolomas:latest"
  volumes:
    - .:/app
  environment:
    - DB_HOST=db
    - DB_PASSWORD=foobar
    - RQ_REDIS_URL=redis://redis:6379/0
  depends_on:
    - db
    - redis

services:
  db:
    image: "timescale/timescaledb-postgis:latest-pg11"
    environment:
      - PYTHONUNBUFFERED=true
      - POSTGRES_PASSWORD=foobar
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"

  app:
    <<: *app-opts
    command: [
      #"wait-for-postgres.sh", "db",
      "pipenv", "run", "./manage.py", "runserver", "0.0.0.0:8000"
    ]
    ports:
      - "8000:8000"

  worker:
    <<: *app-opts
    command: [
      #"wait-for-postgres.sh", "db",
      "pipenv", "run", "./manage.py", "rqworker"
    ]
