version: "3.6"

x-back-opts: &back-opts
  build: .
  image: "geolomas-back:latest"
  env_file:
    - .env
  volumes:
    - .:/app
  depends_on:
    - db
    - redis

services:
  db:
    image: "timescale/timescaledb-postgis:latest-pg11"
    environment:
      - PYTHONUNBUFFERED=true
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"

  api:
    <<: *back-opts
    command: [
      "wait-for-postgres.sh", "db",
      "pipenv", "run", "./manage.py", "runserver", "0.0.0.0:8000"
    ]
    ports:
      - "8000:8000"

  worker:
    <<: *back-opts
    command: [
      "wait-for-postgres.sh", "db",
      "pipenv", "run", "./manage.py", "rqworker"
    ]
